version: "3"

tasks:
  generate:openapi:
    desc: Generate OpenAPI definitions from Go types
    cmds:
      - go install k8s.io/kube-openapi/cmd/openapi-gen@latest
      - |
        openapi-gen \
          --output-dir pkg/openapi \
          --output-pkg github.com/skevetter/agentapi/pkg/openapi \
          --output-file zz_generated.openapi.go \
          github.com/skevetter/agentapi/pkg/apis/devsy/cluster/v1 \
          github.com/skevetter/agentapi/pkg/apis/devsy/storage/v1 \
          github.com/skevetter/admin-apis/pkg/licenseapi \
          k8s.io/apimachinery/pkg/apis/meta/v1 \
          k8s.io/api/core/v1
